<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Services\ProjectStore;
use Illuminate\Console\Command;
use Symfony\Component\Console\Command\Command as SymfonyCommand;

/**
 * Links the current directory to a Jira project by creating .ticket-context.json
 * and ensures .ticket-context/ is added to the project's .gitignore.
 */
class TixLink extends TixCommand
{
    /** @var string */
    protected $signature = 'tix:link
                            {project : Jira project key, e.g. PROJ or APP}';

    /** @var string */
    protected $description = 'Link the current directory to a Jira project';

    public function __construct(private readonly ProjectStore $project)
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $projectKey = strtoupper((string) $this->argument('project'));
        $cwd = (string) getcwd();

        if ($this->project->hasProjectConfig()) {
            $existingKey = $this->project->getProjectKey();
            $configPath = $this->project->getProjectConfigPath();

            if ($existingKey === $projectKey) {
                $this->info("Already linked to {$projectKey} ({$configPath})");

                return SymfonyCommand::SUCCESS;
            }

            if (! $this->confirm("This directory is already linked to {$existingKey}. Re-link to {$projectKey}?")) {
                return SymfonyCommand::SUCCESS;
            }
        }

        $this->project->linkProject($projectKey);

        $this->addToGitignore($cwd);

        $configPath = $this->project->getProjectConfigPath();

        $this->info("Linked {$cwd} → {$projectKey}");
        $this->info("Config saved to: {$configPath}");
        $this->info('');
        $this->info("Now run 'tix sprint' to see your {$projectKey} tickets.");
        $this->info("When starting work, run 'tix branch <KEY>' to create a branch and link your ticket.");

        return SymfonyCommand::SUCCESS;
    }

    /**
     * Ensure generated context files are present in the project's .gitignore.
     * The SKILL.md is intentionally left un-ignored so it can be committed.
     */
    private function addToGitignore(string $projectRoot): void
    {
        $gitignorePath = $projectRoot.'/.gitignore';
        $entry = ProjectStore::CONTEXT_DIR.'/*-context.md';

        if (file_exists($gitignorePath)) {
            $contents = (string) file_get_contents($gitignorePath);

            if (str_contains($contents, $entry)) {
                return;
            }

            file_put_contents($gitignorePath, $contents."\n# Ticket context files (generated by tix)\n{$entry}\n");
        } else {
            file_put_contents($gitignorePath, "# Ticket context files (generated by tix)\n{$entry}\n");
        }

        $this->info("Added {$entry} to .gitignore");
    }
}
